config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'search/index'

  resources :leads do
    collection { post :import }
  end

  get 'welcome/home'

  get 'welcome/about'

  get 'welcome/contact'

  root :to => 'welcome#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  validates_presence_of :name, :company, :location

  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      Lead.create!(row.to_hash)
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |lead|
        csv << lead.attributes.values_at(*column_names)
      end
    end
  end

  def self.text_search(query)
    if query.present?
      where("name @@ :q or company @@ :q", q: query)
      else
        scoped
    end
  end



end

app/models/lead_search.rb
class LeadSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||={}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end

  def scope
    Lead.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /leads
  # GET /leads.json


  def index
    @search = LeadSearch.new(params[:search])
    @leads = @search.scope.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.csv { render text: @leads.to_csv }
      format.json { render json: Lead.limit(100) }
      format.xml { render xml: Lead.limit(50) }
    end

  end

  def import
    Lead.import(params[:file])
    redirect_to leads_url, notice: "Leads imported"
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:name, :company, :location, :phone, :date)
    end

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @leads = Lead.text_search(params[:query])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rapidcrm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/header' %>
<%= yield %>

</div>

</body>
</html>

app/views/leads/_form.html.erb
<% if current_user %>
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :company %><br>
    <%= f.text_field :company, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.number_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create", class: "btn btn-default"  %>
  </div>
<% end %>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Leads</h1>

<h4>Search through the database</h4>
<%= form_tag search_index_path, method: :get do %>
<%= text_field_tag :query, params[:query] %>
<%= submit_tag "Go", class: 'btn' %>
<% end %>

<h4> Select a date range </h4>
<%= form_tag leads_path, method: :get do %>
  <%= text_field_tag 'search[date_from]', @search.date_from %>
  <%= text_field_tag 'search[date_to]', @search.date_to %>
<%= submit_tag "Search", class: 'btn' %>
<% end %>


<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>
						<%= sortable "name" %>
						</th>
						<th>
							Company
						</th>
						<th>
							Location
						</th>
						<th>
							Phone
						</th>
            <% if current_user %>
              <th>
              </th>
            <% end %>
					</tr>
				</thead>
				<tbody>
       <% @leads.each do |lead| %>
					<tr>
						<td>
							<%= lead.name %>
						</td>
						<td>
							<%= lead.company %>
						</td>
						<td>
							<%= lead.location %>
						</td>
						<td>
							<%= lead.phone %>
						</td>
            <% if current_user %>
              <td>
                <%= link_to 'Edit', edit_lead_path(lead) %>
              </td>
            <% end %>
					</tr>
          <% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>

<%= will_paginate @leads %>

<hr>

<%= link_to 'New Lead', new_lead_path %>

<hr>

<div class="well">
  <%= form_tag import_leads_path, multipart: true do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag "Import Leads", class: "btn btn-default" %>
  <% end %>
</div>

<div class="well">
  <h3>Download</h3>
  <%= link_to "Download as CSV", leads_path(format: "csv") %>
</div>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lead.company %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/search/index.html.erb
<h1>Search Results</h1>



<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>
							Name
						</th>
						<th>
							Company
						</th>
						<th>
							Location
						</th>
						<th>
							Phone
						</th>
            <th>
						</th>
					</tr>
				</thead>
				<tbody>
       <% @leads.each do |lead| %>
					<tr>
						<td>
							<%= lead.name %>
						</td>
						<td>
							<%= lead.company %>
						</td>
						<td>
							<%= lead.location %>
						</td>
						<td>
							<%= lead.phone %>
						</td>
            <td>
              <%= link_to 'Edit', edit_lead_path(lead) %>
            </td>
					</tr>
          <% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>

app/views/shared/_header.html.erb
<div class="container">

  <!--    Navigation bar start  -->
  <div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-pills">
				<li>
				<%= link_to "Home", welcome_home_path %>
				</li>
				<li>
  <%= link_to "About US", welcome_about_path %>
				</li>
				<li>
  <%= link_to "Contact", welcome_contact_path %>
        </li>
					<li>
  <%= link_to "Leads", leads_path %>
        </li>
        <% if current_user %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to "Sign In", new_user_session_path %></li>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
			</ul>
		</div>
	</div>
</div>
  <!--    Navigation bar end  -->

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
  </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
  </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
  </div>
  <% end %>

app/views/welcome/about.html.erb
<h1>About Us</h1>
<p>Blah Blah Blah</p>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1>
<p>Blah blah blah</p>

app/views/welcome/home.html.erb
<h1>RapidCRM Homepage</h1>
<p>Hello, Goodbye</p>
<p>To find more about us: <%= link_to "About Us", welcome_about_path %></p>